# Generated by Django 3.0.6 on 2020-08-06 23:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('full_name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('website', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200)),
                ('resume', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('other_material', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobAppStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('talk', 'talked at event'), ('resm', 'gave resume'), ('covr', 'gave cover letter'), ('appl', 'applied via job posting'), ('chln', 'coding challenge/test'), ('intv', 'interview')], default='resm', max_length=50)),
                ('date', models.DateField(default=datetime.date(2020, 8, 6))),
                ('done', models.BooleanField(default=True)),
                ('job_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.JobApp')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('role', models.CharField(choices=[('recr', 'recruiter'), ('head', 'head of something'), ('pers', 'personal contact'), ('misc', 'other')], default='recr', max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Company')),
            ],
        ),
    ]
