# Generated by Django 3.0.6 on 2020-08-09 05:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

	dependencies = [
		('tracker', '0001_initial'),
	]

	operations = [
		migrations.AlterModelOptions(
			name='company',
			options={'verbose_name_plural': 'companies'},
		),
		migrations.AddField(
			model_name='contact',
			name='email',
			field=models.CharField(blank=True, max_length=200),
		),
		migrations.AddField(
			model_name='contact',
			name='phone',
			field=models.CharField(blank=True, max_length=200),
		),
		migrations.AlterField(
			model_name='contact',
			name='name',
			field=models.CharField(max_length=200),
		),
		migrations.AlterField(
			model_name='jobapp',
			name='resume',
			field=models.CharField(max_length=200),
		),
		migrations.AlterField(
			model_name='jobappstep',
			name='date',
			field=models.DateField(default=datetime.date(2020, 8, 9)),
		),
	]
